# Generated by Django 4.1.1 on 2022-12-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apicrud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(blank=True, max_length=300)),
                ('second', models.DateTimeField(auto_now_add=True)),
                ('third', models.IntegerField(default=0)),
                ('fourth', models.EmailField(blank=True, max_length=254)),
                ('fifth', models.BooleanField(default=False)),
                ('sixth', models.ImageField(blank=True, upload_to='images/')),
                ('seventh', models.FileField(blank=True, upload_to='files/')),
                ('eight', models.TextField(blank=True)),
                ('nine', models.CharField(choices=[('TODO', 'TODO'), ('DONE', 'DONE')], default='TODO', max_length=4)),
            ],
            options={
                'ordering': ['second'],
            },
        ),
    ]
